#53 support babashka use httpkit + api updates fro vault 1.7.1 + deps.edn
amperity/vault-clj pull request #54
Opened 2021-07-15 10:23 UTC by ieugen

This is a rough PR - mainly to visualize the amount of changes. 

* I migrated from clj-http to httpkit (API is mostly compatible) - minimal changes
* Added deps.edn for easier consumption of library via git url or local url
* Added bb.edn with sample script to test secret extraction from vault
* Changed clean-body function to make it work with vault 1.7.x API
* Right now 2 tests fail

Fixes #53 

Ideas for improvement:
* Add integration tests using https://www.testcontainers.org/  - start vault in a container and run API tests against it

2021-07-16 01:02 UTC, pyncc requested changes
Nice, thanks for taking the initiative to solve the issue you're facing.

This seems like a reasonable approach, just had a few questions and requests about some of these changes.

Also, congratulations github says this is your first time contributing! 🎉

2021-07-16 07:16 UTC, ieugen commented on src/vault/client/api_util.clj
> +    (throw (RuntimeException.
IllegalStateException was missing from bb https://github.com/babashka/babashka/pull/941 .

2021-07-16 07:17 UTC, ieugen commented on src/vault/lease.clj
> +  (log/debug "Checking for renewable leases...")
It was also missing from bb and was added in the mean time. 
My focus was to make it work.

2021-07-16 07:20 UTC, ieugen commented on src/vault/timer.clj
> +      (catch Exception e
It's missing from babashka. 
I'll see if it makes sense to add it or look for an alternative ( compile conditionals ?!) 
cc @borkdude

2021-07-16 07:22 UTC, ieugen commented on project.clj
> +  ;; :pedantic? :abort
it was failing locally for me. Don't know why.
Now it works.
Restored.

2021-07-16 07:22 UTC, ieugen commented on src/vault/client/api_util.clj
> +(comment
done.

2021-07-16 07:26 UTC, ieugen commented on src/vault/client/api_util.clj
> +    (throw (RuntimeException.
It's added in master but not yet released so I guess this is done.

2021-07-16 07:29 UTC, ieugen commented on dev/user.clj
> +
It's not necessary to keep them but they where very helpful in debugging.
I think they can help others (new contributors esp.) as well.
I would like to keep them if it's all the same, but don't feel strong about this.

2021-07-16 07:43 UTC, ieugen commented on project.clj
> +  ;; :pedantic? :abort
It seems to work only with fully qualified name, even with the patch java.lang.IllegalStateException .
This does not make a difference. 
I've asked for help to see why it is like this though.

2021-07-16 07:49 UTC, borkdude commented on src/vault/timer.clj
> +      (catch Exception e
Yes, we can add it.

2021-07-16 07:52 UTC, ieugen commented on src/vault/timer.clj
> +      (catch Exception e
There is https://github.com/babashka/babashka/pull/943 .

2021-07-16 08:13 UTC, ieugen commented on src/vault/timer.clj
> +      (catch Exception e
Using Interrupted exception, tested with local bb build.

2021-07-16 08:14 UTC, ieugen commented on dev/user.clj
> +
Please reopen if you want me to remove them,

2021-07-16 08:16 UTC, ieugen commented
I've implemented the requested changes. 
It should work with bb from master right now.
I tested only read-secrets, but the others should work as well.

2021-07-16 08:39 UTC, borkdude commented
@ieugen We can add the unit tests of this library to babashka CI. I tend to do this for libraries that are compatible with bb. See test-resources/lib_tests and script/run_lib_tests.

2021-07-19 17:13 UTC, merged

2021-07-19 17:18 UTC, ieugen commented
Thank you @pyncc . 
I'll see if I can write some real integration tests via testcontainers. 

I believe it's better to test against a real, in memory vault instance.

2021-07-19 17:28 UTC, pyncc commented
Release to clojars @ 1.0.4

https://github.com/amperity/vault-clj/releases/tag/1.0.4

> I'll see if I can write some real integration tests via testcontainers.

That sounds good to me, please keep us updated!